[package]
name = "dbs_cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
once_cell = "1.19.0"

[build-dependencies]
serde_json = "1.0.116"
serde = "1.0.198"